version: '2'

networks:
  ecodices_network:
    external:
      name: nginxproxynetwork

services:
  ecodices:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ecodices_app
    restart: always
    environment:
      - VIRTUAL_HOST=ecodices.sd.di.huc.knaw.nl
    volumes:
      - /home/robz/:/home
    networks:
      - ecodices_network

